name: Android Connected Tests w AVD caching

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        api-level: [35]  # 28, 32, 35
        target: [default]  # , google_apis
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :app:connectedDebugAndroidTest

      - name: Upload test reports as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: app/build/reports/androidTests/connected/debug/

#      - name: Capture adb logcat on failure
#        if: failure()  # This runs only if any previous step fails
#        run: |
#          adb logcat > /home/runner/work/Address_Matcher/logcat.log &
#          sleep 15  # Wait for some logs to accumulate
#          cat /home/runner/work/Address_Matcher/logcat.log
#          kill %1  # Kill the adb logcat process after capturing some logs

#      - name: use emulator
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          target: ${{ matrix.target }}
#          arch: x86_64
#          profile: Nexus 6
#          script: |
#            adb devices
#            adb shell getprop
#            adb logcat *:S TestRunner:V -T 1 & LOGCAT_PID=$!
#            ./gradlew :app:connectedDebugAndroidTest
#            if [ -n "$LOGCAT_PID" ] ; then kill $LOGCAT_PID; fi
#            killall -INT crashpad_handler || true
