name: Android CI

on:
  workflow_dispatch:
    inputs:
      BUILD_TOOLS_VERSION:
        description: Android build tools version
        required: true
        default: "35.0.1"

run-name: "BT: ${{ inputs.BUILD_TOOLS_VERSION }}, #${{ github.sha }}"

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables
      run: |
        echo "datestamp=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        # recall with '${{ env.REPO_NAME }}', but only in later steps.

    - name: Show guest OS
      run: |
        cat /etc/os-release
        free -h
        df -h

    - name: List available build tools
      run: |
        ls ${ANDROID_HOME}/build-tools/

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run gradle tests
      run: ./gradlew test

    - name: Build with Gradle
      run: ./gradlew build

#    - name: Build debug APK
#      run: ./gradlew assembleDebug

    - name: Build release APK
      run: ./gradlew assemble

    - name: Sign APK
      run: |
        echo "ANDROID_HOME = $ANDROID_HOME"
        buildTools=${ANDROID_HOME}/build-tools/${{ inputs.BUILD_TOOLS_VERSION }}
        echo "buildTools = $buildTools"
        echo ${{ secrets.SIGNING_KEY }} | base64 -di > my.jks
        ${buildTools}/zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk my-app-unsigned-aligned.apk
        ${buildTools}/apksigner sign --ks my.jks --ks-pass pass:${{ secrets.KEY_STORE_PASSWORD }} --out ${{ env.REPO_NAME }}.apk my-app-unsigned-aligned.apk
        echo "Apk was zip aligned and signed. Now to verify signing"
        ${buildTools}/apksigner verify ${{ env.REPO_NAME }}.apk

    - name: Archive installable signed APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }} ${{ (github.ref_name != 'master' && github.ref_name) || '' }}
        path: ${{ env.REPO_NAME }}.apk

