name: Android CI

on:
  push:
    branches: [ "release/*" ]

  workflow_dispatch:

run-name: ${{ github.sha }} on ${{ github.ref_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set current date as env variable
      run: echo "datestamp=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run gradle tests
      run: ./gradlew test

    - name: Build project with Gradle
      run: ./gradlew build

    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug

    - name: Build apk release project (APK)
      run: ./gradlew assemble

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      env:
        # override default build-tools version (recommended)
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Archive installable signed APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }} ${{ (github.ref_name != 'master' && github.ref_name) || '' }}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

